repos:
  - repo: https://github.com/dbt-opiner/dbt-opiner
    rev: fb7c053
    hooks:
      - id: dbt-opiner-lint
        args: [-f]
        additional_dependencies: [dbt-duckdb == 1.8.2]

  - repo: https://github.com/tconbeer/sqlfmt
    rev: v0.19.2
    hooks:
      - id: sqlfmt
        language_version: python
        additional_dependencies: [".[jinjafmt]"]
        files: ^.*/(models|macros)/.*$ # only run in models and macros folder
        args: ["-l", "99"]
