sqlglot_dialect: duckdb

opinions_config:
  ignore_opinions: None
  ignore_files:
    O005: ".*/models/staging/.*" # Ignore primary key requirement in staging
  extra_opinions_config:
    O002_keywords:
      - summary
      - granularity
  custom_opinions:
    source: git
    repository: https://github.com/dbt-opiner/dbt-opiner-custom-opinions.git
    #rev: 2348b98 # Tag or commit sha, not branches.

files:
  sql: ".*/(models|macros|tests)/.*"
  #yaml:
  #md:
